apiVersion: v1
kind: Service
metadata:
  name: k8s-example
  namespace: my-namespace
spec:
  selector:
    app: k8s-example
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort