apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-example
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: k8s-example
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-example
    spec:
      containers:
        - name: k8s-example
          image: saricanziyadocker/k8s-example:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
